name: pagein
summary: tool to force swapped out pages back into memory
description: Pagein is a tool that forces pages that are in swap to be paged in back to memory.  The main usecase for pagein is to exercise the VM and swap subsystems for testing purposes.
confinement: devmode
type: app
grade: stable
assumes: [snapd2.45]
base: core20
adopt-info: pagein

architectures:
    - build-on: s390x
    - build-on: ppc64el
    - build-on: arm64
    - build-on: armhf
    - build-on: amd64
    - build-on: i386

parts:
    pagein:
        plugin: make
        source-type: git
        source: https://github.com/ColinIanKing/pagein
        override-pull: |
            snapcraftctl pull
            description="$(git describe HEAD --tags)"
            sha=$(echo $description | tr '-' ' ' | awk '{print $NF}')
            version=${description%$sha}
            commits=$(git log --oneline | wc -l)
            date=$(date +'%Y%m%d')
            if test "$description" = "$sha"
            then
                version="$description"
            else
                version=$(echo $version$date-$commits-$sha | cut -c1-32)
            fi
            snapcraftctl set-version "$version"
        build-packages:
            - gcc
            - make

apps:
    pagein:
        command: usr/bin/pagein

