name: pagein
version: git
version-script: |
    echo $(git describe --tags)
summary: tool to force swapped out pages back into memory
description: Pagein is a tool that forces pages that are in swap to be paged in back to memory.  The main usecase for pagein is to exercise the VM and swap subsystems for testing purposes.
confinement: devmode
type: app
grade: stable

parts:
    pagein:
        plugin: make
        source: git://github.com/ColinIanKing/pagein
        build-packages:
            - gcc
            - make

apps:
    pagein:
        command: usr/bin/pagein

